### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by eitsupi** [gitbucket/gitbucket-pages-plugin#34]
I see that a new version of GitBucket has been released, are there any plans to release a new version of this plugin that will be bundled with?

Thank you for your continuous development.

**Comment by takezoe** [comment]
Ah, we should have released a new version for GitBucket 4.36.x. The next release will be for GitBucket 4.37.x but we don't have a specific plan for that yet. If you need new features of this plugin, we will release a new version independently from GitBucket release so that you can use new version of this plugin by installing yourself.

**Comment by eitsupi** [comment]
Thanks for your reply. If you could create a release of this plugin, I would be happy!

**Comment by takezoe** [comment]
Released: https://github.com/gitbucket/gitbucket-pages-plugin/releases/tag/1.10.0
