### ISSUE TITLE
Allow to select a directory!

### ISSUE THREAD

**Issue by eprozium** [gitbucket/gitbucket-pages-plugin#7]
Allow to select a directory, e.g. /docs instead of a branch.

**Comment by yaroot** [comment]
Providing options and switches will complicate things a lot. And I do think an orphan branch for generated documents make more sense than including them in source branch (automate it via jenkins or other CI).

What's your thought?

**Comment by aadrian** [comment]
>  I do think an orphan branch for generated documents make more sense than including them in source branch

That depends on the use case. For some developers it might be, but for most users (many of them are not even developers) it's not and it's a PITA to manage an orphan branch (I had to explain this "feature" countless times even to developers).

Also please note that GitHub now allows exactly this feature :) 
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by yaroot** [comment]
Well, that's some work to create the options, for now they could create a new repo with `gb-pages` branch to contain only documents. I'll reopen this issue if someone wants to contribute.

**Comment by shiena** [comment]
@yaroot I am just making source selection features.
https://github.com/shiena/gitbucket-pages-plugin/tree/pages-option

This patch does not work yet because it uses the following features before release.
https://github.com/gitbucket/gitbucket/issues/1477

So, I am planning to submit a pull request when the next version of GitBucket is released.

![image](https://cloud.githubusercontent.com/assets/1295639/23798262/26f3f90c-05e7-11e7-9c24-d7970d71e2b1.png)

**Comment by yaroot** [comment]
@shiena Hi, thanks for contributing, could you open a PR right away?

**Comment by shiena** [comment]
@yaroot OK. I opened #14
